 SET SEARCH_PATH TO :SCHEMA_NAME;
 TRUNCATE batch_job_execution CASCADE;
 TRUNCATE batch_job_execution_context CASCADE;
 TRUNCATE batch_job_execution_params CASCADE;
 TRUNCATE batch_job_instance CASCADE;
 TRUNCATE batch_step_execution CASCADE;
 TRUNCATE batch_step_execution_context CASCADE;
 TRUNCATE ref_billing_status CASCADE;
 TRUNCATE ref_category CASCADE;
 TRUNCATE ref_inventory CASCADE;
 TRUNCATE ref_product CASCADE;
 TRUNCATE ref_product_status CASCADE;
 TRUNCATE tab_address CASCADE;
 TRUNCATE tab_billing CASCADE;
 TRUNCATE tab_metadonnees CASCADE;
 TRUNCATE tab_orders CASCADE;
 TRUNCATE tab_person CASCADE;
 TRUNCATE tab_product CASCADE;